spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=student
    username: sa
    password: 081199th
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.SQLServer2019Dialect
      ddl-auto: none
      jdbc:
         lob:
            non_contextual_creation: true
      temp:
          use_jdbc_metadata_defaults: false
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
server:
  port: 8000