spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/student?autoReconnect=true
    username: postgres
    password: 081199th
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
      jdbc:
         lob:
            non_contextual_creation: true
      temp:
          use_jdbc_metadata_defaults: false
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
server:
  port: 8000